import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import { useEffect, useState } from 'react';
import { SignUp, useUser, SignedOut } from '@clerk/nextjs';
import { useRouter } from 'next/router';

export default function SignUpPage() {
  const [loading, setLoading] = useState(true);
  const router = useRouter();
  const { user, isSignedIn } = useUser();

  useEffect(() => {
    setLoading(false);
  }, []);

  useEffect(() => {
    if (isSignedIn) {
      router.push('/dashboard');
    }
  }, [isSignedIn]);

  if (loading) {
    return <span>loading...</span>;
  } else {
    return (
      <>
        <Head>
          <title>Note Capsule</title>
          <meta name='description' content='Generated by create next app' />
          <meta name='viewport' content='width=device-width, initial-scale=1' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <main>
          <SignedOut>
            <SignUp />
          </SignedOut>
        </main>
      </>
    );
  }
}
