import Head from "next/head";
import { Inter } from "next/font/google";
import { useEffect, useState } from "react";
import { Button } from "react-bootstrap";
import { SignIn, SignUpButton, SignedIn, SignedOut } from "@clerk/nextjs";
// import Login from "../components/login";

const inter = Inter({ subsets: ["latin"] });

export default function SignInPage() {
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    setLoading(false);
  }, []);

  if (loading) {
    return <span>loading...</span>;
  } else {
    return (
      <>
        <Head>
          <title>Note Capsule</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <SignedOut>
            <SignIn />
          </SignedOut>
        </main>
      </>
    );
  }
}
