import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'
import { SignUp, SignedOut } from "@clerk/nextjs";
import { Button } from 'react-bootstrap'
// import Login from '../components/login';

const inter = Inter({ subsets: ['latin'] })

export default function SignUpPage() {

  const [posts, setPosts] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    setLoading(false);
  }, []);

  if(loading) {
    return (<span>loading...</span>);
  } else {
    return (
      <>
        <Head>
          <title>Note Capsule</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
            <SignUp />
        </main>
      </>
    )
  }
}
