// import Head from "next/head";
// import { useEffect, useState } from "react";
// import Link from "next/link";
// import { Button, Form } from "react-bootstrap";
// import * as db from "../modules/Data";

// export default function Login(props) {

//   const [loading, setLoading] = useState(true);

//   useEffect(() => {
//     setLoading(false);
//   }, []);

//   async function handleSubmit(e) {
//     e.preventDefault();
//     console.log("test");
//     const email_address = e.target.email_address.value;
//     const password = e.target.password.value;
//     if(props.isLogin){
//       const result = db.addSignIn(email_address, password);
//       console.log(result);
//     } else{
//       const result = db.addSignUp(email_address, password);
//       console.log(result);
//     }
    
//   }

//   if (loading) {
//     return <span>loading...</span>;
//   } else {
//     return (
//       <>
//         <Head>
//           <title>Note Capsule</title>
//           <meta name="description" content="Generated by create next app" />
//           <meta name="viewport" content="width=device-width, initial-scale=1" />
//           <link rel="icon" href="/favicon.ico" />
//         </Head>
//         <main>
//           <div>
//             <form method="post" onSubmit={(e) => handleSubmit(e)}>
//               <input type="email" name="email_address" placeholder="Phone number or email"></input> <br></br>
//               <input type="password" name="password" placeholder="Password"></input> <br></br>
//               {props.isLogin ? (
//                 <button type="submit" href="/login">
//                   Log In
//                 </button>
//               ) : (
//                 <button type="submit" href="/signup">
//                   Sign up
//                 </button>
//               )}
//             </form>
//           </div>

//           <div>
//             {props.isLogin ? (
//               <>
//                 <p>Don't have an account?</p>
//                 <Link href="/signup">Sign up</Link>
//               </>
//             ) : (
//               <>
//                 <p>Already have an account?</p>
//                 <Link href="/login">Log In</Link>
//               </>
//             )}
//           </div>
//         </main>
//       </>
//     );
//   }
// }
